### ISSUE TITLE
vdoing 引入报错插件

### ISSUE THREAD

**Issue by BruceBat818** [u2sb/vuepress-plugin-mmedia#8]
插件版本：1.5.3
使用环境：v-doing中
视频说明：项目中仅使用本地视频，未引用B站视频
报错说明：打开项目主页就报错，未打开具体文档
报错信息：
Uncaught SyntaxError: Unexpected token ':' (at BilibiliComponent.js:38:29)
    at ./node_modules/vuepress-plugin-smplayer/components/Bilibili/BilibiliComponent.js (app.js:4980:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (enhanceAppFile.js?3b7b:1:1)
    at ./node_modules/vuepress-plugin-smplayer/utils/enhanceAppFile.js (app.js:5076:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (4.js?162f:1:1)
    at ./node_modules/@vuepress/core/.temp/app-enhancers/4.js (app.js:1116:1)
    at __webpack_require__ (app.js:833:30)
./node_modules/vuepress-plugin-smplayer/components/Bilibili/BilibiliComponent.js @ app.js:4980
__webpack_require__ @ app.js:833
fn @ app.js:130
eval @ enhanceAppFile.js?3b7b:1
./node_modules/vuepress-plugin-smplayer/utils/enhanceAppFile.js @ app.js:5076
__webpack_require__ @ app.js:833
fn @ app.js:130
eval @ 4.js?162f:1
./node_modules/@vuepress/core/.temp/app-enhancers/4.js @ app.js:1116
__webpack_require__ @ app.js:833
fn @ app.js:130
eval @ app-enhancers.js?110a:1
./node_modules/@vuepress/core/.temp/internal/app-enhancers.js @ app.js:1152
__webpack_require__ @ app.js:833
fn @ app.js:130
eval @ app.js?63b8:1
./node_modules/@vuepress/core/lib/client/app.js @ app.js:1259
__webpack_require__ @ app.js:833
fn @ app.js:130
eval @ clientEntry.js?3501:1
./node_modules/@vuepress/core/lib/client/clientEntry.js @ app.js:1271
__webpack_require__ @ app.js:833
fn @ app.js:130
0 @ app.js:5455
__webpack_require__ @ app.js:833
(anonymous) @ app.js:971
(anonymous) @ app.js:974

**Comment by BruceBat818** [comment]
开发工具，webstorm

**Comment by BruceBat818** [comment]
能否解答一下，比较着急，感谢

**Comment by BruceBat818** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/13620382/187194348-bd5c6cc2-d6c9-4c67-9664-664ad337dc25.png">

**Comment by MonoLogueChi** [comment]
抱歉，最近比较忙一直没有回复，可以尝试一下相同的开发环境下，使用模板 https://github.com/u2sb/vuepress-theme-vdoing-template 是否会报错
